name: CRD
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install rclone
        sudo apt install wget
        sudo apt install pip
        sudo apt update
        sudo apt-get install -y wget
        sudo wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg --install chrome-remote-desktop_current_amd64.deb
        sudo apt install -y --fix-broken
        sudo DEBIAN_FRONTEND=noninteractive apt install -y xfce4 desktop-base
        sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
        sudo apt install -y xscreensaver
        sudo apt install -y task-xfce-desktop
    - name: Downloading
      run: |
        wget https://raw.githubusercontent.com/HeroBenHero/Scripts/main/CRD.sh
        sudo chmod 777 CRD.sh
        sudo bash CRD.sh
